##Q1. What are the benefits of the built-in array package, if any?
### ANS The array module provides an efficient way to store and manipulate arrays of homogeneous data types. Arrays created with the array module are more memory-efficient than traditional Python lists because they store data in a contiguous block of memory. This reduces memory overhead and can be particularly useful when dealing with large datasets.



##Q2. What are some of the array package&#39;s limitations?
### ANS Arrays created with the array module can only store elements of a single data type. This means that if you need to work with heterogeneous data, such as a combination of integers, floats, and strings, you would need to use a different data structure like a list or a NumPy array.
###Compared to more specialized libraries like NumPy, the array module provides a relatively limited set of operations and functions. It doesn't have advanced mathematical functions or a wide range of array manipulation methods. If you require complex array operations, you may find NumPy or other scientific computing libraries more suitable.
###The array module does not provide advanced indexing and slicing capabilities like those found in NumPy arrays. You can only access elements using integer indices and perform basic slicing operations.



##Q3. Describe the main differences between the array and numpy packages.

### ANS **Array Package**
####The array module in Python's standard library provides a basic array data structure with limited functionality. It supports efficient storage and manipulation of arrays of a single data type but lacks advanced mathematical functions and array manipulation capabilities.
####The array module enforces a single data type for all elements in an array. When creating an array with the array module, you specify the data type, such as integers or floating-point numbers, and all elements must be of that type.

### **NumPy**
####NumPy (Numerical Python) is a powerful third-party library specifically designed for numerical computing in Python. It offers a wide range of functionality, including advanced mathematical operations, array manipulation methods, linear algebra routines, Fourier transforms, random number generation, and more. NumPy provides multidimensional arrays (ndarrays) as a core data structure, which allows for efficient and flexible handling of arrays.
####NumPy supports arrays of various data types, including integers, floats, booleans, and more. NumPy's ndarray allows for heterogeneous arrays, meaning different elements within the same array can have different data types. This flexibility is useful when working with complex data sets or mixed data types.

##Q4. Explain the distinctions between the empty, ones, and zeros functions.

### ANS The **empty()** function creates a new array without initializing its elements to any particular values. It allocates the required memory for the array but does not set any initial values. 
###The **ones()** function creates a new array and initializes all its elements to the value 1. You can specify the shape of the array as a tuple or as individual dimensions. The data type of the array is by default float64, but you can specify a different data type using the dtype parameter.
###The **zeros()** function creates a new array and initializes all its elements to the value 0. It is similar to the ones() function, but instead of filling the array with 1s, it fills it with 0s. The shape of the array can be specified using a tuple or individual dimensions, and you can also specify the data type using the dtype parameter.

##Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

### ANS Its function is to execute the function over each coordinate and the resulting array. The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis.

##Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

### ANS  If any scaler value such as integer is added to the numpy array then all the elements inside the array will add that value in it.



In [2]:
# Example
import numpy as np
a= np.arange(9).reshape(3,3)
print(a)
print('-----------')
print(a+1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

### ANS It will do the operation as per operators. Like if we use + operand it will update the current array by adding and when we use '*', it will update by multiplying.

In [3]:
# Example
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
a += 2
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
a *= 2
print(a)

[[ 4  6  8]
 [10 12 14]
 [16 18 20]]


##Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

### ANS Yes it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array containing string values is the maximum length of any string present in the array.Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit.

In [6]:
# Example
import numpy as np
a = np.array(['abc','defg','hijk'])
a

array(['abc', 'defg', 'hijk'], dtype='<U4')

In [7]:
a[a=='abc']='lmnopq'
print(a)

['lmno' 'defg' 'hijk']


##Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?
### ANS It will simply add or multiply element to element at same position.The only requirement which must be met are:
###1)Data type should be same.
###2) Shape of the two matrices must be same.



In [10]:
# Example
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
b = a+3
print(b)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
a+b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [13]:
a*b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

##Q10. What is the best way to use a Boolean array to mask another array?



In [15]:
## ANS
x = np.array([True,True,False,True])          
y = np.array([1,2,3,4])         
m = np.ma.masked_where(y>2,x)  
print(list(m))
print(m.ndim)

[True, True, masked, masked]
1


##Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.
### ANS NumPy:
####NumPy provides a function called numpy.std() that calculates the standard deviation of an array efficiently. It is typically the fastest method due to its optimized implementation in C.

###Statistics module (Standard Python):
####The statistics module in standard Python provides a function called statistics.stdev() to calculate the standard deviation of a list of numbers. Although it is implemented in pure Python, it is still reasonably fast for most common use cases.

###Math module (Standard Python):
####The math module in standard Python provides a function called math.sqrt() that can be used in conjunction with other mathematical operations to calculate the standard deviation. This method involves more manual calculations and can be slower than the previous two methods.


In [17]:
# Example
# using numpy
import numpy as np

data = np.array([1, 2, 3, 4, 5])
std = np.std(data)
print(std)

1.4142135623730951


In [18]:
# using statistics
import statistics

data = [1, 2, 3, 4, 5]
std = statistics.stdev(data)
print(std)

1.5811388300841898


In [19]:
# using math module
import math

data = [1, 2, 3, 4, 5]
mean = sum(data) / len(data)
variance = sum((x - mean) ** 2 for x in data) / len(data)
std = math.sqrt(variance)
print(std)


1.4142135623730951


##12. What is the dimensionality of a Boolean mask-generated array?
### ANS The dimensionality of a Boolean mask-generated array depends on the shape of the original array and the logic used to create the mask.

###A Boolean mask is an array consisting of Boolean values (True or False) that can be used to select elements from another array. When applying a Boolean mask to an array, the resulting array will have the same dimensionality as the original array, but with only the elements selected by the mask.